// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetSubscriptionsParams creates a new GetSubscriptionsParams object
//
// There are no default values defined in the spec.
func NewGetSubscriptionsParams() GetSubscriptionsParams {

	return GetSubscriptionsParams{}
}

// GetSubscriptionsParams contains all the bound params for the get subscriptions operation
// typically these are obtained from a http.Request
//
// swagger:parameters getSubscriptions
type GetSubscriptionsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Email address to look up subscriptions for
	  Required: true
	  In: query
	*/
	Email string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetSubscriptionsParams() beforehand.
func (o *GetSubscriptionsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r
	qs := runtime.Values(r.URL.Query())

	qEmail, qhkEmail, _ := qs.GetOK("email")
	if err := o.bindEmail(qEmail, qhkEmail, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmail binds and validates parameter Email from query.
func (o *GetSubscriptionsParams) bindEmail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("email", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false

	if err := validate.RequiredString("email", "query", raw); err != nil {
		return err
	}
	o.Email = raw

	return nil
}
