// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetSubscriptionsHandlerFunc turns a function with the right signature into a get subscriptions handler
type GetSubscriptionsHandlerFunc func(GetSubscriptionsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetSubscriptionsHandlerFunc) Handle(params GetSubscriptionsParams) middleware.Responder {
	return fn(params)
}

// GetSubscriptionsHandler interface for that can handle valid get subscriptions params
type GetSubscriptionsHandler interface {
	Handle(GetSubscriptionsParams) middleware.Responder
}

// NewGetSubscriptions creates a new http.Handler for the get subscriptions operation
func NewGetSubscriptions(ctx *middleware.Context, handler GetSubscriptionsHandler) *GetSubscriptions {
	return &GetSubscriptions{Context: ctx, Handler: handler}
}

/*
	GetSubscriptions swagger:route GET /subscriptions subscription getSubscriptions

# Get subscriptions for an email

Returns all active subscriptions for the given email address.
*/
type GetSubscriptions struct {
	Context *middleware.Context
	Handler GetSubscriptionsHandler
}

func (o *GetSubscriptions) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetSubscriptionsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
