// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	stderrors "errors"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// SubscribeMaxParseMemory sets the maximum size in bytes for
// the multipart form parser for this operation.
//
// The default value is 32 MB.
// The multipart parser stores up to this + 10MB.
var SubscribeMaxParseMemory int64 = 32 << 20

// NewSubscribeParams creates a new SubscribeParams object
//
// There are no default values defined in the spec.
func NewSubscribeParams() SubscribeParams {

	return SubscribeParams{}
}

// SubscribeParams contains all the bound params for the subscribe operation
// typically these are obtained from a http.Request
//
// swagger:parameters subscribe
type SubscribeParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Email address to subscribe
	  Required: true
	  In: formData
	*/
	Email string

	/*GitHub repository in owner/repo format (e.g., golang/go)
	  Required: true
	  In: formData
	*/
	Repo string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewSubscribeParams() beforehand.
func (o *SubscribeParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := r.ParseMultipartForm(SubscribeMaxParseMemory); err != nil {
		if !stderrors.Is(err, http.ErrNotMultipart) {
			return errors.New(400, "%v", err)
		} else if errParse := r.ParseForm(); errParse != nil {
			return errors.New(400, "%v", errParse)
		}
	}
	fds := runtime.Values(r.Form)

	fdEmail, fdhkEmail, _ := fds.GetOK("email")
	if err := o.bindEmail(fdEmail, fdhkEmail, route.Formats); err != nil {
		res = append(res, err)
	}

	fdRepo, fdhkRepo, _ := fds.GetOK("repo")
	if err := o.bindRepo(fdRepo, fdhkRepo, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindEmail binds and validates parameter Email from formData.
func (o *SubscribeParams) bindEmail(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("email", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("email", "formData", raw); err != nil {
		return err
	}
	o.Email = raw

	return nil
}

// bindRepo binds and validates parameter Repo from formData.
func (o *SubscribeParams) bindRepo(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("repo", "formData", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("repo", "formData", raw); err != nil {
		return err
	}
	o.Repo = raw

	return nil
}
