version: "2"
run:
  issues-exit-code: 1
  tests: true
  build-tags:
    - e2e
    - integration

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - funlen
    - gocognit
    - gocyclo
    - godoclint
    - godox
    - ireturn
    - lll
    - mnd
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - tagalign
    - testpackage
    - varnamelen
    - wastedassign
    - wsl
    - wsl_v5

  settings:
    decorder:
      dec-order:
        - const
        - type
        - var
        - func
      disable-dec-order-check: false
      disable-init-func-first-check: false
    gocognit:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enable-all: true
      disabled-checks:
        - exitAfterDefer
    gocyclo:
      min-complexity: 10
    godot:
      scope: toplevel
      capital: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
        - shadow
    ineffassign:
      check-escaping-errors: true
    misspell:
      locale: US
    perfsprint:
      integer-format: true
      int-conversion: true
      error-format: true
      err-error: true
      errorf: true
      string-format: true
      sprintf1: true
      strconcat: true
      bool-format: true
      hex-format: true
      concat-loop: true
      loop-other-ops: true
    revive:
      confidence: 0.6
      enable-default-rules: true
      rules:
        - name: add-constant
          disabled: true
        - name: argument-limit
        - name: atomic
        - name: banned-characters
        - name: bare-return
        - name: blank-imports
          disabled: true
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: comment-spacings
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
          arguments:
            - allowTypesBefore: '*testing.T'
        - name: context-keys-type
        - name: datarace
        - name: deep-exit
          disabled: true
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: enforce-map-style
        - name: enforce-repeated-arg-type-style
        - name: enforce-slice-style
        - name: enforce-switch-style
        - name: epoch-naming
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: exported
          disabled: true
        - name: file-header
          disabled: true
        - name: file-length-limit
          disabled: true
        - name: filename-format
          arguments:
            - ^[_a-z][_a-z0-9]*.go$
        - name: flag-parameter
          disabled: true
        - name: forbidden-call-in-wg-go
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: get-return
        - name: identical-branches
        - name: identical-ifelseif-branches
        - name: identical-ifelseif-conditions
        - name: identical-switch-branches
        - name: identical-switch-conditions
        - name: if-return
        - name: import-alias-naming
        - name: import-shadowing
          disabled: true
        - name: imports-blocklist
          disabled: true
        - name: increment-decrement
        - name: indent-error-flow
        - name: inefficient-map-lookup
        - name: line-length-limit
          arguments:
            - 140
        - name: max-control-nesting
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: nested-structs
          disabled: true
        - name: optimize-operands-order
        - name: package-comments
          disabled: true
        - name: package-directory-mismatch
        - name: range
        - name: range-val-address
        - name: range-val-in-closure
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: redundant-import-alias
        - name: string-format
        - name: string-of-int
        - name: struct-tag
          arguments:
            - json,inline
        - name: superfluous-else
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
          disabled: true
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
          disabled: true
        - name: unnecessary-format
          disabled: true
        - name: unnecessary-if
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unsecure-url-scheme
        - name: unused-parameter
        - name: unused-receiver
          disabled: true
        - name: use-any
          disabled: true
        - name: use-errors-new
        - name: use-fmt-print
        - name: use-slices-sort
        - name: use-waitgroup-go
        - name: useless-break
        - name: useless-fallthrough
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    staticcheck:
      checks:
        - all
        # Incorrect or missing package comment https://staticcheck.dev/docs/checks/#ST1000
        - -ST1000
    testifylint:
      enable-all: true
    unparam:
      check-exported: true
    unqueryvet:
      check-sql-builders: true
      check-aliased-wildcard: true
      check-string-concat: true
      check-format-strings: true
      check-string-builder: true
      check-subqueries: true
      check-n1: true
      check-sql-injection: true
      check-tx-leaks: true
    usetesting:
      context-background: true
      context-todo: true
      os-chdir: true
      os-mkdir-temp: true
      os-setenv: true
      os-temp-dir: true
      os-create-temp: true
    usestdlibvars:
      http-method: true
      http-status-code: true
      time-weekday: true
      time-month: true
      time-layout: true
      time-date-month: true
      crypto-hash: true
      default-rpc-path: true
      sql-isolation-level: true
      tls-signature-scheme: true
      constant-kind: true
  exclusions:
    warn-unused: true
    rules:
      - source: "^//go:generate "
        linters: [revive]
      - source: "httptest."
        linters: [noctx]
      - path: _test\.go$
        linters:
          - decorder
          - gosec
          - wrapcheck
      - text: "get-return: function 'getConfirm' seems to be a getter but it does not return any result"
        linters: [revive]

formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule
    gofumpt:
      extra-rules: true
