// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "GitHub Release Notification API that allows users to subscribe to email notifications about new releases of a chosen GitHub repository.",
    "title": "GitHub Release Notification API",
    "version": "1.0.0"
  },
  "host": "releases-api.app",
  "basePath": "/api",
  "paths": {
    "/confirm/{token}": {
      "get": {
        "description": "Confirms a subscription using the token sent in the confirmation email.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Confirm email subscription",
        "operationId": "confirmSubscription",
        "parameters": [
          {
            "type": "string",
            "description": "Confirmation token",
            "name": "token",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Subscription confirmed successfully"
          },
          "400": {
            "description": "Invalid token"
          },
          "404": {
            "description": "Token not found"
          }
        }
      }
    },
    "/subscribe": {
      "post": {
        "description": "Subscribe an email to receive notifications about new releases of a GitHub repository. The repository is validated via GitHub API.",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Subscribe to release notifications",
        "operationId": "subscribe",
        "parameters": [
          {
            "type": "string",
            "description": "Email address to subscribe",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "GitHub repository in owner/repo format (e.g., golang/go)",
            "name": "repo",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Subscription successful. Confirmation email sent."
          },
          "400": {
            "description": "Invalid input (e.g., invalid repo format)"
          },
          "404": {
            "description": "Repository not found on GitHub"
          },
          "409": {
            "description": "Email already subscribed to this repository"
          }
        }
      }
    },
    "/subscriptions": {
      "get": {
        "description": "Returns all active subscriptions for the given email address.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Get subscriptions for an email",
        "operationId": "getSubscriptions",
        "parameters": [
          {
            "type": "string",
            "description": "Email address to look up subscriptions for",
            "name": "email",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation - list of subscriptions returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Subscription"
              }
            }
          },
          "400": {
            "description": "Invalid email"
          }
        }
      }
    },
    "/unsubscribe/{token}": {
      "get": {
        "description": "Unsubscribes an email from release notifications using the token sent in emails.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Unsubscribe from release notifications",
        "operationId": "unsubscribe",
        "parameters": [
          {
            "type": "string",
            "description": "Unsubscribe token",
            "name": "token",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Unsubscribed successfully"
          },
          "400": {
            "description": "Invalid token"
          },
          "404": {
            "description": "Token not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Subscription": {
      "type": "object",
      "required": [
        "email",
        "repo"
      ],
      "properties": {
        "confirmed": {
          "description": "Whether the subscription is confirmed",
          "type": "boolean"
        },
        "email": {
          "description": "Email address",
          "type": "string"
        },
        "last_seen_tag": {
          "description": "Last seen release tag for this repository",
          "type": "string"
        },
        "repo": {
          "description": "GitHub repository in owner/repo format",
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Subscription management operations",
      "name": "subscription"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "GitHub Release Notification API that allows users to subscribe to email notifications about new releases of a chosen GitHub repository.",
    "title": "GitHub Release Notification API",
    "version": "1.0.0"
  },
  "host": "releases-api.app",
  "basePath": "/api",
  "paths": {
    "/confirm/{token}": {
      "get": {
        "description": "Confirms a subscription using the token sent in the confirmation email.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Confirm email subscription",
        "operationId": "confirmSubscription",
        "parameters": [
          {
            "type": "string",
            "description": "Confirmation token",
            "name": "token",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Subscription confirmed successfully"
          },
          "400": {
            "description": "Invalid token"
          },
          "404": {
            "description": "Token not found"
          }
        }
      }
    },
    "/subscribe": {
      "post": {
        "description": "Subscribe an email to receive notifications about new releases of a GitHub repository. The repository is validated via GitHub API.",
        "consumes": [
          "application/json",
          "application/x-www-form-urlencoded"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Subscribe to release notifications",
        "operationId": "subscribe",
        "parameters": [
          {
            "type": "string",
            "description": "Email address to subscribe",
            "name": "email",
            "in": "formData",
            "required": true
          },
          {
            "type": "string",
            "description": "GitHub repository in owner/repo format (e.g., golang/go)",
            "name": "repo",
            "in": "formData",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Subscription successful. Confirmation email sent."
          },
          "400": {
            "description": "Invalid input (e.g., invalid repo format)"
          },
          "404": {
            "description": "Repository not found on GitHub"
          },
          "409": {
            "description": "Email already subscribed to this repository"
          }
        }
      }
    },
    "/subscriptions": {
      "get": {
        "description": "Returns all active subscriptions for the given email address.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Get subscriptions for an email",
        "operationId": "getSubscriptions",
        "parameters": [
          {
            "type": "string",
            "description": "Email address to look up subscriptions for",
            "name": "email",
            "in": "query",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation - list of subscriptions returned",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Subscription"
              }
            }
          },
          "400": {
            "description": "Invalid email"
          }
        }
      }
    },
    "/unsubscribe/{token}": {
      "get": {
        "description": "Unsubscribes an email from release notifications using the token sent in emails.",
        "produces": [
          "application/json"
        ],
        "tags": [
          "subscription"
        ],
        "summary": "Unsubscribe from release notifications",
        "operationId": "unsubscribe",
        "parameters": [
          {
            "type": "string",
            "description": "Unsubscribe token",
            "name": "token",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Unsubscribed successfully"
          },
          "400": {
            "description": "Invalid token"
          },
          "404": {
            "description": "Token not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Subscription": {
      "type": "object",
      "required": [
        "email",
        "repo"
      ],
      "properties": {
        "confirmed": {
          "description": "Whether the subscription is confirmed",
          "type": "boolean"
        },
        "email": {
          "description": "Email address",
          "type": "string"
        },
        "last_seen_tag": {
          "description": "Last seen release tag for this repository",
          "type": "string"
        },
        "repo": {
          "description": "GitHub repository in owner/repo format",
          "type": "string"
        }
      }
    }
  },
  "tags": [
    {
      "description": "Subscription management operations",
      "name": "subscription"
    }
  ]
}`))
}
