// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/dmytrovoron/github-release-notification/internal/service/api/models"
)

// GetSubscriptionsOKCode is the HTTP code returned for type GetSubscriptionsOK
const GetSubscriptionsOKCode int = 200

/*
GetSubscriptionsOK Successful operation - list of subscriptions returned

swagger:response getSubscriptionsOK
*/
type GetSubscriptionsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Subscription `json:"body,omitempty"`
}

// NewGetSubscriptionsOK creates GetSubscriptionsOK with default headers values
func NewGetSubscriptionsOK() *GetSubscriptionsOK {

	return &GetSubscriptionsOK{}
}

// WithPayload adds the payload to the get subscriptions o k response
func (o *GetSubscriptionsOK) WithPayload(payload []*models.Subscription) *GetSubscriptionsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get subscriptions o k response
func (o *GetSubscriptionsOK) SetPayload(payload []*models.Subscription) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetSubscriptionsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Subscription, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetSubscriptionsBadRequestCode is the HTTP code returned for type GetSubscriptionsBadRequest
const GetSubscriptionsBadRequestCode int = 400

/*
GetSubscriptionsBadRequest Invalid email

swagger:response getSubscriptionsBadRequest
*/
type GetSubscriptionsBadRequest struct {
}

// NewGetSubscriptionsBadRequest creates GetSubscriptionsBadRequest with default headers values
func NewGetSubscriptionsBadRequest() *GetSubscriptionsBadRequest {

	return &GetSubscriptionsBadRequest{}
}

// WriteResponse to the client
func (o *GetSubscriptionsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(400)
}
