// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewConfirmSubscriptionParams creates a new ConfirmSubscriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewConfirmSubscriptionParams() *ConfirmSubscriptionParams {
	return &ConfirmSubscriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewConfirmSubscriptionParamsWithTimeout creates a new ConfirmSubscriptionParams object
// with the ability to set a timeout on a request.
func NewConfirmSubscriptionParamsWithTimeout(timeout time.Duration) *ConfirmSubscriptionParams {
	return &ConfirmSubscriptionParams{
		timeout: timeout,
	}
}

// NewConfirmSubscriptionParamsWithContext creates a new ConfirmSubscriptionParams object
// with the ability to set a context for a request.
func NewConfirmSubscriptionParamsWithContext(ctx context.Context) *ConfirmSubscriptionParams {
	return &ConfirmSubscriptionParams{
		Context: ctx,
	}
}

// NewConfirmSubscriptionParamsWithHTTPClient creates a new ConfirmSubscriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewConfirmSubscriptionParamsWithHTTPClient(client *http.Client) *ConfirmSubscriptionParams {
	return &ConfirmSubscriptionParams{
		HTTPClient: client,
	}
}

/*
ConfirmSubscriptionParams contains all the parameters to send to the API endpoint

	for the confirm subscription operation.

	Typically these are written to a http.Request.
*/
type ConfirmSubscriptionParams struct {

	/* Token.

	   Confirmation token
	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the confirm subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfirmSubscriptionParams) WithDefaults() *ConfirmSubscriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the confirm subscription params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ConfirmSubscriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the confirm subscription params
func (o *ConfirmSubscriptionParams) WithTimeout(timeout time.Duration) *ConfirmSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the confirm subscription params
func (o *ConfirmSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the confirm subscription params
func (o *ConfirmSubscriptionParams) WithContext(ctx context.Context) *ConfirmSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the confirm subscription params
func (o *ConfirmSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the confirm subscription params
func (o *ConfirmSubscriptionParams) WithHTTPClient(client *http.Client) *ConfirmSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the confirm subscription params
func (o *ConfirmSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the confirm subscription params
func (o *ConfirmSubscriptionParams) WithToken(token string) *ConfirmSubscriptionParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the confirm subscription params
func (o *ConfirmSubscriptionParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *ConfirmSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
