// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ConfirmSubscriptionReader is a Reader for the ConfirmSubscription structure.
type ConfirmSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ConfirmSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewConfirmSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewConfirmSubscriptionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewConfirmSubscriptionNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /confirm/{token}] confirmSubscription", response, response.Code())
	}
}

// NewConfirmSubscriptionOK creates a ConfirmSubscriptionOK with default headers values
func NewConfirmSubscriptionOK() *ConfirmSubscriptionOK {
	return &ConfirmSubscriptionOK{}
}

/*
ConfirmSubscriptionOK describes a response with status code 200, with default header values.

Subscription confirmed successfully
*/
type ConfirmSubscriptionOK struct {
}

// IsSuccess returns true when this confirm subscription o k response has a 2xx status code
func (o *ConfirmSubscriptionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this confirm subscription o k response has a 3xx status code
func (o *ConfirmSubscriptionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this confirm subscription o k response has a 4xx status code
func (o *ConfirmSubscriptionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this confirm subscription o k response has a 5xx status code
func (o *ConfirmSubscriptionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this confirm subscription o k response a status code equal to that given
func (o *ConfirmSubscriptionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the confirm subscription o k response
func (o *ConfirmSubscriptionOK) Code() int {
	return 200
}

func (o *ConfirmSubscriptionOK) Error() string {
	return fmt.Sprintf("[GET /confirm/{token}][%d] confirmSubscriptionOK", 200)
}

func (o *ConfirmSubscriptionOK) String() string {
	return fmt.Sprintf("[GET /confirm/{token}][%d] confirmSubscriptionOK", 200)
}

func (o *ConfirmSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewConfirmSubscriptionBadRequest creates a ConfirmSubscriptionBadRequest with default headers values
func NewConfirmSubscriptionBadRequest() *ConfirmSubscriptionBadRequest {
	return &ConfirmSubscriptionBadRequest{}
}

/*
ConfirmSubscriptionBadRequest describes a response with status code 400, with default header values.

Invalid token
*/
type ConfirmSubscriptionBadRequest struct {
}

// IsSuccess returns true when this confirm subscription bad request response has a 2xx status code
func (o *ConfirmSubscriptionBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this confirm subscription bad request response has a 3xx status code
func (o *ConfirmSubscriptionBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this confirm subscription bad request response has a 4xx status code
func (o *ConfirmSubscriptionBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this confirm subscription bad request response has a 5xx status code
func (o *ConfirmSubscriptionBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this confirm subscription bad request response a status code equal to that given
func (o *ConfirmSubscriptionBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the confirm subscription bad request response
func (o *ConfirmSubscriptionBadRequest) Code() int {
	return 400
}

func (o *ConfirmSubscriptionBadRequest) Error() string {
	return fmt.Sprintf("[GET /confirm/{token}][%d] confirmSubscriptionBadRequest", 400)
}

func (o *ConfirmSubscriptionBadRequest) String() string {
	return fmt.Sprintf("[GET /confirm/{token}][%d] confirmSubscriptionBadRequest", 400)
}

func (o *ConfirmSubscriptionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewConfirmSubscriptionNotFound creates a ConfirmSubscriptionNotFound with default headers values
func NewConfirmSubscriptionNotFound() *ConfirmSubscriptionNotFound {
	return &ConfirmSubscriptionNotFound{}
}

/*
ConfirmSubscriptionNotFound describes a response with status code 404, with default header values.

Token not found
*/
type ConfirmSubscriptionNotFound struct {
}

// IsSuccess returns true when this confirm subscription not found response has a 2xx status code
func (o *ConfirmSubscriptionNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this confirm subscription not found response has a 3xx status code
func (o *ConfirmSubscriptionNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this confirm subscription not found response has a 4xx status code
func (o *ConfirmSubscriptionNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this confirm subscription not found response has a 5xx status code
func (o *ConfirmSubscriptionNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this confirm subscription not found response a status code equal to that given
func (o *ConfirmSubscriptionNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the confirm subscription not found response
func (o *ConfirmSubscriptionNotFound) Code() int {
	return 404
}

func (o *ConfirmSubscriptionNotFound) Error() string {
	return fmt.Sprintf("[GET /confirm/{token}][%d] confirmSubscriptionNotFound", 404)
}

func (o *ConfirmSubscriptionNotFound) String() string {
	return fmt.Sprintf("[GET /confirm/{token}][%d] confirmSubscriptionNotFound", 404)
}

func (o *ConfirmSubscriptionNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
