// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dmytrovoron/github-release-notification/tests/http/models"
)

// GetSubscriptionsReader is a Reader for the GetSubscriptions structure.
type GetSubscriptionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetSubscriptionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetSubscriptionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetSubscriptionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /subscriptions] getSubscriptions", response, response.Code())
	}
}

// NewGetSubscriptionsOK creates a GetSubscriptionsOK with default headers values
func NewGetSubscriptionsOK() *GetSubscriptionsOK {
	return &GetSubscriptionsOK{}
}

/*
GetSubscriptionsOK describes a response with status code 200, with default header values.

Successful operation - list of subscriptions returned
*/
type GetSubscriptionsOK struct {
	Payload []*models.Subscription
}

// IsSuccess returns true when this get subscriptions o k response has a 2xx status code
func (o *GetSubscriptionsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get subscriptions o k response has a 3xx status code
func (o *GetSubscriptionsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get subscriptions o k response has a 4xx status code
func (o *GetSubscriptionsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get subscriptions o k response has a 5xx status code
func (o *GetSubscriptionsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get subscriptions o k response a status code equal to that given
func (o *GetSubscriptionsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get subscriptions o k response
func (o *GetSubscriptionsOK) Code() int {
	return 200
}

func (o *GetSubscriptionsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscriptions][%d] getSubscriptionsOK %s", 200, payload)
}

func (o *GetSubscriptionsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /subscriptions][%d] getSubscriptionsOK %s", 200, payload)
}

func (o *GetSubscriptionsOK) GetPayload() []*models.Subscription {
	return o.Payload
}

func (o *GetSubscriptionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetSubscriptionsBadRequest creates a GetSubscriptionsBadRequest with default headers values
func NewGetSubscriptionsBadRequest() *GetSubscriptionsBadRequest {
	return &GetSubscriptionsBadRequest{}
}

/*
GetSubscriptionsBadRequest describes a response with status code 400, with default header values.

Invalid email
*/
type GetSubscriptionsBadRequest struct {
}

// IsSuccess returns true when this get subscriptions bad request response has a 2xx status code
func (o *GetSubscriptionsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get subscriptions bad request response has a 3xx status code
func (o *GetSubscriptionsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get subscriptions bad request response has a 4xx status code
func (o *GetSubscriptionsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get subscriptions bad request response has a 5xx status code
func (o *GetSubscriptionsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get subscriptions bad request response a status code equal to that given
func (o *GetSubscriptionsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get subscriptions bad request response
func (o *GetSubscriptionsBadRequest) Code() int {
	return 400
}

func (o *GetSubscriptionsBadRequest) Error() string {
	return fmt.Sprintf("[GET /subscriptions][%d] getSubscriptionsBadRequest", 400)
}

func (o *GetSubscriptionsBadRequest) String() string {
	return fmt.Sprintf("[GET /subscriptions][%d] getSubscriptionsBadRequest", 400)
}

func (o *GetSubscriptionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
