// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// SubscribeReader is a Reader for the Subscribe structure.
type SubscribeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SubscribeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewSubscribeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewSubscribeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewSubscribeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewSubscribeConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /subscribe] subscribe", response, response.Code())
	}
}

// NewSubscribeOK creates a SubscribeOK with default headers values
func NewSubscribeOK() *SubscribeOK {
	return &SubscribeOK{}
}

/*
SubscribeOK describes a response with status code 200, with default header values.

Subscription successful. Confirmation email sent.
*/
type SubscribeOK struct {
}

// IsSuccess returns true when this subscribe o k response has a 2xx status code
func (o *SubscribeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this subscribe o k response has a 3xx status code
func (o *SubscribeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this subscribe o k response has a 4xx status code
func (o *SubscribeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this subscribe o k response has a 5xx status code
func (o *SubscribeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this subscribe o k response a status code equal to that given
func (o *SubscribeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the subscribe o k response
func (o *SubscribeOK) Code() int {
	return 200
}

func (o *SubscribeOK) Error() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeOK", 200)
}

func (o *SubscribeOK) String() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeOK", 200)
}

func (o *SubscribeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubscribeBadRequest creates a SubscribeBadRequest with default headers values
func NewSubscribeBadRequest() *SubscribeBadRequest {
	return &SubscribeBadRequest{}
}

/*
SubscribeBadRequest describes a response with status code 400, with default header values.

Invalid input (e.g., invalid repo format)
*/
type SubscribeBadRequest struct {
}

// IsSuccess returns true when this subscribe bad request response has a 2xx status code
func (o *SubscribeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this subscribe bad request response has a 3xx status code
func (o *SubscribeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this subscribe bad request response has a 4xx status code
func (o *SubscribeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this subscribe bad request response has a 5xx status code
func (o *SubscribeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this subscribe bad request response a status code equal to that given
func (o *SubscribeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the subscribe bad request response
func (o *SubscribeBadRequest) Code() int {
	return 400
}

func (o *SubscribeBadRequest) Error() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeBadRequest", 400)
}

func (o *SubscribeBadRequest) String() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeBadRequest", 400)
}

func (o *SubscribeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubscribeNotFound creates a SubscribeNotFound with default headers values
func NewSubscribeNotFound() *SubscribeNotFound {
	return &SubscribeNotFound{}
}

/*
SubscribeNotFound describes a response with status code 404, with default header values.

Repository not found on GitHub
*/
type SubscribeNotFound struct {
}

// IsSuccess returns true when this subscribe not found response has a 2xx status code
func (o *SubscribeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this subscribe not found response has a 3xx status code
func (o *SubscribeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this subscribe not found response has a 4xx status code
func (o *SubscribeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this subscribe not found response has a 5xx status code
func (o *SubscribeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this subscribe not found response a status code equal to that given
func (o *SubscribeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the subscribe not found response
func (o *SubscribeNotFound) Code() int {
	return 404
}

func (o *SubscribeNotFound) Error() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeNotFound", 404)
}

func (o *SubscribeNotFound) String() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeNotFound", 404)
}

func (o *SubscribeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSubscribeConflict creates a SubscribeConflict with default headers values
func NewSubscribeConflict() *SubscribeConflict {
	return &SubscribeConflict{}
}

/*
SubscribeConflict describes a response with status code 409, with default header values.

Email already subscribed to this repository
*/
type SubscribeConflict struct {
}

// IsSuccess returns true when this subscribe conflict response has a 2xx status code
func (o *SubscribeConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this subscribe conflict response has a 3xx status code
func (o *SubscribeConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this subscribe conflict response has a 4xx status code
func (o *SubscribeConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this subscribe conflict response has a 5xx status code
func (o *SubscribeConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this subscribe conflict response a status code equal to that given
func (o *SubscribeConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the subscribe conflict response
func (o *SubscribeConflict) Code() int {
	return 409
}

func (o *SubscribeConflict) Error() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeConflict", 409)
}

func (o *SubscribeConflict) String() string {
	return fmt.Sprintf("[POST /subscribe][%d] subscribeConflict", 409)
}

func (o *SubscribeConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
