// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// UnsubscribeReader is a Reader for the Unsubscribe structure.
type UnsubscribeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UnsubscribeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewUnsubscribeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewUnsubscribeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUnsubscribeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /unsubscribe/{token}] unsubscribe", response, response.Code())
	}
}

// NewUnsubscribeOK creates a UnsubscribeOK with default headers values
func NewUnsubscribeOK() *UnsubscribeOK {
	return &UnsubscribeOK{}
}

/*
UnsubscribeOK describes a response with status code 200, with default header values.

Unsubscribed successfully
*/
type UnsubscribeOK struct {
}

// IsSuccess returns true when this unsubscribe o k response has a 2xx status code
func (o *UnsubscribeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this unsubscribe o k response has a 3xx status code
func (o *UnsubscribeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unsubscribe o k response has a 4xx status code
func (o *UnsubscribeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this unsubscribe o k response has a 5xx status code
func (o *UnsubscribeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this unsubscribe o k response a status code equal to that given
func (o *UnsubscribeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the unsubscribe o k response
func (o *UnsubscribeOK) Code() int {
	return 200
}

func (o *UnsubscribeOK) Error() string {
	return fmt.Sprintf("[GET /unsubscribe/{token}][%d] unsubscribeOK", 200)
}

func (o *UnsubscribeOK) String() string {
	return fmt.Sprintf("[GET /unsubscribe/{token}][%d] unsubscribeOK", 200)
}

func (o *UnsubscribeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnsubscribeBadRequest creates a UnsubscribeBadRequest with default headers values
func NewUnsubscribeBadRequest() *UnsubscribeBadRequest {
	return &UnsubscribeBadRequest{}
}

/*
UnsubscribeBadRequest describes a response with status code 400, with default header values.

Invalid token
*/
type UnsubscribeBadRequest struct {
}

// IsSuccess returns true when this unsubscribe bad request response has a 2xx status code
func (o *UnsubscribeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unsubscribe bad request response has a 3xx status code
func (o *UnsubscribeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unsubscribe bad request response has a 4xx status code
func (o *UnsubscribeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this unsubscribe bad request response has a 5xx status code
func (o *UnsubscribeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this unsubscribe bad request response a status code equal to that given
func (o *UnsubscribeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the unsubscribe bad request response
func (o *UnsubscribeBadRequest) Code() int {
	return 400
}

func (o *UnsubscribeBadRequest) Error() string {
	return fmt.Sprintf("[GET /unsubscribe/{token}][%d] unsubscribeBadRequest", 400)
}

func (o *UnsubscribeBadRequest) String() string {
	return fmt.Sprintf("[GET /unsubscribe/{token}][%d] unsubscribeBadRequest", 400)
}

func (o *UnsubscribeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUnsubscribeNotFound creates a UnsubscribeNotFound with default headers values
func NewUnsubscribeNotFound() *UnsubscribeNotFound {
	return &UnsubscribeNotFound{}
}

/*
UnsubscribeNotFound describes a response with status code 404, with default header values.

Token not found
*/
type UnsubscribeNotFound struct {
}

// IsSuccess returns true when this unsubscribe not found response has a 2xx status code
func (o *UnsubscribeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this unsubscribe not found response has a 3xx status code
func (o *UnsubscribeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this unsubscribe not found response has a 4xx status code
func (o *UnsubscribeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this unsubscribe not found response has a 5xx status code
func (o *UnsubscribeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this unsubscribe not found response a status code equal to that given
func (o *UnsubscribeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the unsubscribe not found response
func (o *UnsubscribeNotFound) Code() int {
	return 404
}

func (o *UnsubscribeNotFound) Error() string {
	return fmt.Sprintf("[GET /unsubscribe/{token}][%d] unsubscribeNotFound", 404)
}

func (o *UnsubscribeNotFound) String() string {
	return fmt.Sprintf("[GET /unsubscribe/{token}][%d] unsubscribeNotFound", 404)
}

func (o *UnsubscribeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
