// Code generated by go-swagger; DO NOT EDIT.

package subscription

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewUnsubscribeParams creates a new UnsubscribeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUnsubscribeParams() *UnsubscribeParams {
	return &UnsubscribeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUnsubscribeParamsWithTimeout creates a new UnsubscribeParams object
// with the ability to set a timeout on a request.
func NewUnsubscribeParamsWithTimeout(timeout time.Duration) *UnsubscribeParams {
	return &UnsubscribeParams{
		timeout: timeout,
	}
}

// NewUnsubscribeParamsWithContext creates a new UnsubscribeParams object
// with the ability to set a context for a request.
func NewUnsubscribeParamsWithContext(ctx context.Context) *UnsubscribeParams {
	return &UnsubscribeParams{
		Context: ctx,
	}
}

// NewUnsubscribeParamsWithHTTPClient creates a new UnsubscribeParams object
// with the ability to set a custom HTTPClient for a request.
func NewUnsubscribeParamsWithHTTPClient(client *http.Client) *UnsubscribeParams {
	return &UnsubscribeParams{
		HTTPClient: client,
	}
}

/*
UnsubscribeParams contains all the parameters to send to the API endpoint

	for the unsubscribe operation.

	Typically these are written to a http.Request.
*/
type UnsubscribeParams struct {

	/* Token.

	   Unsubscribe token
	*/
	Token string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the unsubscribe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnsubscribeParams) WithDefaults() *UnsubscribeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the unsubscribe params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UnsubscribeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the unsubscribe params
func (o *UnsubscribeParams) WithTimeout(timeout time.Duration) *UnsubscribeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the unsubscribe params
func (o *UnsubscribeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the unsubscribe params
func (o *UnsubscribeParams) WithContext(ctx context.Context) *UnsubscribeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the unsubscribe params
func (o *UnsubscribeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the unsubscribe params
func (o *UnsubscribeParams) WithHTTPClient(client *http.Client) *UnsubscribeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the unsubscribe params
func (o *UnsubscribeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithToken adds the token to the unsubscribe params
func (o *UnsubscribeParams) WithToken(token string) *UnsubscribeParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the unsubscribe params
func (o *UnsubscribeParams) SetToken(token string) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *UnsubscribeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param token
	if err := r.SetPathParam("token", o.Token); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
