// Code generated by go-swagger; DO NOT EDIT.

// Package restapi GitHub Release Notification API
//
//	GitHub Release Notification API that allows users to subscribe to email notifications about new releases of a chosen GitHub repository.
//	Schemes:
//	  http
//	  https
//	Host: releases-api.app
//	BasePath: /api
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//	  - application/x-www-form-urlencoded
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
